name: Sync cn_dicts directory

# 设置触发条件
on:
    schedule:
        # 每天早上5点执行 (UTC 21:00 = 北京时间次日 5:00)
        - cron: '0 21 * * *'
    workflow_dispatch: # 允许手动触发

jobs:
    sync-directories:
        runs-on: ubuntu-latest
        permissions:
            contents: write # 需要写入权限

        steps:
            - name: Checkout destination repository
              uses: actions/checkout@v4
              with:
                  repository: 'astralwaveio/rime_autosync'
                  ref: 'main'
                  fetch-depth: 1

            - name: Setup Git Identity
              run: |
                  git config user.name "GitHub Sync Bot"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            - name: Clone source repository
              run: |
                  git clone --depth 1 https://github.com/amzxyz/RIME-LMDG.git /tmp/source-repo

            - name: Synchronize cn_dicts directory
              run: |
                  # 确保源目录存在
                  if [ ! -d "/tmp/source-repo/cn_dicts" ]; then
                    echo "Error: Source directory doesn't exist"
                    exit 1
                  fi

                  # 移除目标目录
                  rm -rf cn_dicts
                  mkdir -p cn_dicts

                  # 复制源仓库中的内容
                  cp -rf /tmp/source-repo/cn_dicts/* cn_dicts/

                  echo "Directory synchronized"

            - name: Check for changes
              id: check_changes
              run: |
                  git add -A cn_dicts/
                  if git diff --staged --quiet; then
                    echo "No changes detected in cn_dicts directory"
                    echo "changes_detected=false" >> $GITHUB_OUTPUT
                  else
                    echo "Changes detected in cn_dicts directory"
                    echo "changes_detected=true" >> $GITHUB_OUTPUT
                  fi

            - name: Commit and push changes
              if: steps.check_changes.outputs.changes_detected == 'true'
              run: |
                  # 获取当前日期作为提交消息的一部分
                  DATE=$(date '+%Y-%m-%d')
                  git commit -m "Auto-sync cn_dicts directory from RIME-LMDG on $DATE"
                  git push
                  echo "Changes committed and pushed successfully"
